name: Docker Image CI - consumer

on:
  push:
    branches: 
      - "main"
    paths: 
      - 'lab_2/consumer/consumer.py'
jobs:
  editorconfig:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  build:
    needs: [editorconfig]
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure Container Apps Build and Deploy
      uses: Azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }}/lab_2/producer/
        acrName: oblakcontainer
        containerAppName: consumer
        resourceGroup: fervjestina
        dockerfilePath: ${{ github.workspace }}/lab_2/consumer/Dockerfile
